Lesson 4: add appeals (web and api)
m0rphhh/fefu_backend_3_6 pull request #4
Opened 2022-04-07 02:57 UTC by m0rphhh

2022-04-12 00:30 UTC, chrn-feip requested changes

2022-04-12 00:30 UTC, chrn-feip commented on app/Http/Controllers/Api/AppealController.php
> +    #[OpenApi\Operation(tags: ['appeals'])]
Уточните, что метод POST

2022-04-12 00:30 UTC, chrn-feip commented on app/Http/Controllers/Api/AppealController.php
> +        $data['phone'] = PhoneSanitizer::sanitize($request->input('phone'));
Предусмотрите значение по умолчанию на случай, если опциональных телефона и почты в запросе не будет, потестируйте апи с их отсутствием

2022-04-12 00:30 UTC, chrn-feip commented on app/Http/Requests/AppealFormRequest.php
> +            'phone' => 'nullable',
где регулярка на телефон?

2022-04-12 00:30 UTC, chrn-feip commented on database/factories/AppealFactory.php
> +class AppealFactory extends Factory
Это не нужно

2022-04-12 00:30 UTC, chrn-feip commented on database/seeders/AppealSeeder.php
> +class AppealSeeder extends Seeder
Это не нужно

2022-04-12 00:30 UTC, chrn-feip commented on app/Http/Controllers/Api/AppealController.php
> +    #[OpenApi\Response(factory: AppealValidationErrorsResponse::class, statusCode: 422)]
Вы тестировали код? Уверены, что в случае ошибок валидации получите в ответ json ожидаемой структуры?

2022-04-22 12:35 UTC, m0rphhh commented on app/Http/Controllers/Api/AppealController.php
> +    #[OpenApi\Response(factory: AppealValidationErrorsResponse::class, statusCode: 422)]
тестировал, структура похожа

2022-04-22 12:38 UTC, m0rphhh commented on app/Http/Controllers/Api/AppealController.php
> +        $data['phone'] = PhoneSanitizer::sanitize($request->input('phone'));
немного не понимаю "значение о умолчанию"
если поля телефона и почты не заполнить, в базу попадут null

2022-05-02 09:33 UTC, merged